before_install:
  - "sudo bash -c 'echo 127.0.0.1 localhost local.dev > /etc/hosts'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget https://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar"
  - "java -jar selenium-server-standalone-2.25.0.jar > /dev/null 2>&1 &"
  - "sleep 30"
before_script:
    - "cd test/integration && bundle install; cd ../.."
script: test/integration/run
